# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

senslope <- function(y, x = NULL) {
    .Call(`_rtrend_senslope`, y, x)
}

Sf <- function(x) {
    .Call(`_rtrend_Sf`, x)
}

varS <- function(x, rof, S) {
    .Call(`_rtrend_varS`, x, rof, S)
}

